name: Deploy 
on: 
  push:
    branches:
      - feature/17
jobs:
  build:
    runs-on: ubuntu-20.04 
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Check Node v
        run: node -v
      - name: Install Dependencies 
        run: npm install
      - name: Build 
        run: npm run build
      - name: zip create 
        run: zip -qq -r ./review.zip . 
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
      - name: Upload to S3 
        run: | 
          aws s3 cp --region ap-northeast-2 ./review.zip s3://review-s3-bucket-lee/review.zip
      - name: Deploy 
        run: aws deploy create-deployment
          --application-name review-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce 
          --deployment-group-name review-deploy-group
          --s3-location bucket=review-s3-bucket-lee,key=review.zip,bundleType=zip